import = ["~/.config/alacritty/themes/themes/catppuccin_frappe.toml.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
option_as_alt = "OnlyRight"


opacity = 0.5
blur = true   #Macos

decorations = "Buttonless"

[font]
size = 14.0

[font.bold]
family = "MesloLGS Nerd Font Propo"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font Propo"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font Propo"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Propo"
style = "Regular"
