import = ["~/.config/alacritty/themes/themes/citylights.toml"]
[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10


opacity = 0.8
blur = "true" #Macos

decorations = "Buttonless"

size = 19
