import = ["~/.config/alacritty/themes/themes/citylights.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10


opacity = 0.8
blur = "true" #Macos

decorations = "Buttonless"

[font]
size = 9.0

[font.bold]
family = "Meslo LG S Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Meslo LG S Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Meslo LG S Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Meslo LG S Nerd Font Mono"
style = "Regular"
