return {
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "stylua",
        "shellcheck",
        "shfmt",
        "flake8",
        "astro-language-server",
        "clangd",
        "codelldb",
        "cpptools",
        "css-lsp",
        "eslint-lsp",
        "java-debug-adapter",
        "java-test",
        "jdtls",
        "js-debug-adapter",
        "json-lsp",
        "lua-language-server",
        "prettierd",
        "prisma-language-server",
        "pyright",
        "rust-analyzer",
        "shfmt",
        "stylua",
        "taplo",
        "typescript-language-server",
        "zls",
        "docker-compose-language-service",
        "dockerfile-language-server",
      },
    },
  },
}
